## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

In [2]:
# 1.

# Para saber o percentual de acerto por aluno, por disciplina basta dividir os dataframes das matérias pela quantidade total de questões por disciplina.

porcentagem_matematica = df_mat / 24
porcentagem_portugues = df_por / 18
porcentagem_geografia = df_geo / 8
porcentagem_ingles = df_ing / 8
porcentagem_historia = df_his / 8
porcentagem_fisica = df_fis / 12
porcentagem_quimica = df_qui / 12

# Como exemplo do output usarei a matéria de matemática.

porcentagem_matematica.round(decimals= 2) # Utilizei o método round para arredondar o valor para duas casas decimais.

    Qt_acertos
0         0.25
1         0.79
2         0.58
3         0.42
4         0.29
..         ...
95        0.25
96        0.33
97        0.96
98        0.00
99        0.46

[100 rows x 1 columns]

In [3]:
# 2.

# Para saber o total de acerto por aluno basta somar todos os dataframes.

total_alunos = df_mat + df_por + df_geo + df_ing + df_his + df_fis + df_qui

total_alunos

    Qt_acertos
0           35
1           48
2           50
3           32
4           30
..         ...
95          34
96          27
97          40
98          40
99          42

[100 rows x 1 columns]

In [4]:
# 3.

# Para saber a porcentagem geral de cada aluno basta dividir a quantidade de acerto de cada aluno pela quantidade total de questões

total_questões = 24 + 18 + 8 + 8 + 8 + 12 + 12

porcentagem_geral = total_alunos / total_questões

porcentagem_geral.round(decimals= 2)

    Qt_acertos
0         0.39
1         0.53
2         0.56
3         0.36
4         0.33
..         ...
95        0.38
96        0.30
97        0.44
98        0.44
99        0.47

[100 rows x 1 columns]

In [5]:
# 4.

# O enunciado pede a quantidade de alunos que acertaram MAIS de 45 questões.

# Peguei o dataframe da quantidade de acertos por aluno, filtrei para aqueles que acertaram mais que 45 questões, e realizei a contagem.
total_alunos[total_alunos['Qt_acertos'] > 45].value_counts()

# Aqui é apresentado a quantidade de alunos que acertou mais que 45 questões por quantidade de questões acertadas, se quisermos saber o total basta colocar um .sum() no final

Qt_acertos
50            7
48            5
53            3
46            2
49            2
52            2
55            2
56            2
47            1
54            1
58            1
62            1
63            1
66            1
dtype: int64

In [6]:
total_alunos[total_alunos['Qt_acertos'] > 45].value_counts().sum()

31

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [7]:
# Como eu estava com dificuldade de realizar essa segunda parte achei mais fácil colocar todos os dados em um único dataframe.


df_total = df_mat + df_por + df_geo + df_ing + df_his + df_fis + df_qui # Soma o total de questões acertadas para cada aluno.

df_geral = df_mat
df_geral['Qt_acertos_mat'] = df_mat['Qt_acertos']
df_geral['Qt_acertos_por'] = df_por['Qt_acertos']
df_geral['Qt_acertos_geo'] = df_geo['Qt_acertos']
df_geral['Qt_acertos_his'] = df_his['Qt_acertos']
df_geral['Qt_acertos_ing'] = df_ing['Qt_acertos']
df_geral['Qt_acertos_fis'] = df_fis['Qt_acertos']
df_geral['Qt_acertos_qui'] = df_qui['Qt_acertos']
df_geral['Total_acertos'] = df_total['Qt_acertos']

df_geral.drop(columns='Qt_acertos', inplace=True)
df_geral

,Qt_acertos_mat,Qt_acertos_por,Qt_acertos_geo,Qt_acertos_his,Qt_acertos_ing,Qt_acertos_fis,Qt_acertos_qui,Total_acertos
0,6,7,7,1,3,8,3,35
1,19,10,0,0,0,11,8,48
2,14,16,0,7,5,4,4,50
3,10,7,3,0,4,0,8,32
4,7,2,2,0,7,9,3,30
...,...,...,...,...,...,...,...,...
95,6,4,7,4,1,9,3,34
96,8,1,4,1,6,4,3,27
97,23,5,0,4,2,1,5,40
98,0,10,3,5,1,10,11,40
99,11,15,0,6,1,7,2,42

In [8]:
# 1.

# Para saber quais alunos foram reprovados, filtrei o dataframe.

df_reprovados = df_geral[(df_geral['Qt_acertos_mat'] == 0) |
                         (df_geral['Qt_acertos_fis'] == 0) |
                         (df_geral['Qt_acertos_qui'] == 0)]

df_reprovados

,Qt_acertos_mat,Qt_acertos_por,Qt_acertos_geo,Qt_acertos_his,Qt_acertos_ing,Qt_acertos_fis,Qt_acertos_qui,Total_acertos
3,10,7,3,0,4,0,8,32
6,6,0,7,5,7,0,4,29
10,10,8,3,1,2,7,0,31
12,20,8,3,1,7,0,3,42
14,7,11,1,1,7,4,0,31
20,23,11,6,6,5,2,0,53
25,0,4,7,0,4,4,8,27
26,11,14,6,7,2,0,0,40
27,21,13,1,7,5,3,0,50
33,14,8,0,6,5,6,0,39
35,11,14,6,3,3,0,11,48
49,8,1,1,1,0,0,8,19
56,7,6,7,6,5,0,8,39
65,1,8,2,3,4,0,6,24
66,5,4,3,3,6,0,10,31
72,11,16,3,7,4,0,9,50
73,1,16,2,3,4,0,11,37
74,9,11,0,5,7,7,0,39
84,15,1,0,1,5,0,4,26
89,23,11,7,6,7,9,0,63
92,14,10,1,1,6,8,0,40
94,0,5,2,1,6,3,8,25
98,0,10,3,5,1,10,11,40

In [9]:
# 2.

# Para saber a quantidade de alunos que reprovaram utilizei o método shape que dá o formato do dataframe.

df_reprovados.shape

(23, 8)

In [10]:
# 3.

# Filtrei as notas de história dos alunos reprovados e utilizei o método mean() para obter a média.

df_reprovados_his = df_reprovados['Qt_acertos_his']

df_reprovados_his.mean()

3.4347826086956523

In [11]:
# 3.

# Filtrei as notas de geografia dos alunos reprovados e utilizei o método mean() para obter a média.

df_reprovados_geo = df_reprovados['Qt_acertos_geo']

df_reprovados_geo.mean()

3.217391304347826

In [13]:
# 4.

# Para saber quais alunos não reprovaram utilizei o método drop na base de dados.
# Depois filtrei pela nota de corte, > 45 acertos.

reprovados_index = df_reprovados.index

df_nao_reprovados = df_geral.drop(reprovados_index)

df_aprovados = df_nao_reprovados[df_nao_reprovados['Total_acertos'] > 45]

df_aprovados

,Qt_acertos_mat,Qt_acertos_por,Qt_acertos_geo,Qt_acertos_his,Qt_acertos_ing,Qt_acertos_fis,Qt_acertos_qui,Total_acertos
1,19,10,0,0,0,11,8,48
2,14,16,0,7,5,4,4,50
5,20,2,5,2,3,9,9,50
7,18,4,4,7,7,1,8,49
8,22,9,2,6,7,5,7,58
17,21,15,2,4,2,2,6,52
18,20,4,3,3,5,11,4,50
24,20,2,7,3,5,11,2,50
31,15,13,3,3,1,9,10,54
36,22,9,6,1,6,4,8,56
37,19,12,5,1,7,6,2,52
39,4,16,2,6,4,9,8,49
40,18,3,6,6,3,5,6,47
42,20,6,7,2,7,3,3,48
45,17,10,0,6,2,9,4,48
48,17,6,0,5,7,9,11,55
60,16,8,0,4,4,7,9,48
62,17,6,2,7,4,1,9,46
67,21,0,7,4,2,2,10,46
70,21,14,0,5,3,11,8,62
71,17,8,7,4,6,2,9,53
77,15,2,5,6,7,11,7,53
78,14,16,7,7,2,11,9,66
81,22,16,2,4,0,1,10,55
88,20,1,1,7,5,9,7,50
93,12,16,5,6,5,6,6,56

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [22]:
arquivo = r"C:\Users\kenji\OneDrive\Documentos\EBAC\Ciêntista de dados\Módulo 4\Tarefa 03 - 05\Registros de vacinacao covid ACRE.csv"

# Caminho do arquivo em csv

In [23]:
df = pd.read_csv(arquivo, sep=';')

# Lendo o arquivo csv

In [24]:
df.head(10)

,document_id,paciente_id,paciente_idade,paciente_datanascimento,paciente_enumsexobiologico,paciente_racacor_codigo,paciente_racacor_valor,paciente_endereco_coibgemunicipio,paciente_endereco_copais,paciente_endereco_nmmunicipio,...,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataaplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem,data_importacao_rnds,id_sistema_origem
0,b19cd280-474c-4c22-a35d-8c06bc04a4e0-i0b0,2e091c9a37d3f50d1d705fc80c6448c6fc69b44da9e936...,69,1951-12-28,F,3,PARDA,120050.0,10.0,SENA MADUREIRA,...,210052A,FUNDACAO BUTANTAN,Organization/61189445000156,2021-03-23,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-03-25T03:27:19.000Z,NaN
1,a1acc0b6-1cf6-4c4b-adcb-06b473a0faaf-i0b0,f4e17a9e5354cb45e223d85eda02fb2f76048c801675f5...,81,1939-11-22,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,210110,FUNDACAO BUTANTAN,Organization/61189445000156,2021-04-29,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-04-30T16:03:14.000Z,NaN
2,af279a98-ba1f-47ea-8214-314a98040b0d-i0b0,6734b26bccf826130ebffa66575977bbe71477b12bcf42...,69,1951-08-14,M,4,AMARELA,120020.0,10.0,CRUZEIRO DO SUL,...,210135,FUNDACAO BUTANTAN,Organization/61189445000156,2021-04-16,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-04-16T15:54:39.000Z,NaN
3,4879308e-5050-46bb-b8e2-11fa5646a05c-i0b0,84a341fd350c1ba7117fccbb4d2df417bc0fac0fffac37...,51,1969-12-15,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,202010040,FUNDACAO BUTANTAN,Organization/61189445000156,2021-02-19,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-03-10T14:40:54.000Z,NaN
4,000e911b-e3a4-4114-a735-d1f2e6e3797f-i0b0,c59571e19f368d4b0cf08cd3bcabb32e5cd8baad5340f6...,65,1955-11-21,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,212VCD001ZVB,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-03-29,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-04-03T19:44:28.000Z,NaN
5,13dac96a-cdab-49a8-8c2a-0341c8b2638c-i0b0,8683cf7321f3e93aae6e12448f4ebfc4828f4aef7d5b25...,56,1964-05-25,M,99,SEM INFORMACAO,NaN,NaN,NaN,...,202010028,FUNDACAO BUTANTAN,Organization/61189445000156,2021-03-25,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-04-12T20:36:34.000Z,NaN
6,852365aa-108b-4aa2-ae39-7b5d46149678-i0b0,33950e1cfc224c872655e817922f304e87ffae6e049363...,65,1955-09-25,M,4,AMARELA,120050.0,10.0,SENA MADUREIRA,...,212VCD001ZVB,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-03-30,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-04-06T16:34:46.000Z,NaN
7,9ef6e305-609d-4e4e-a0c2-e43a8139922d-i0b0,0e5f337f0b289810dbe9c40de2faabe482e3fd08047920...,39,1981-11-02,M,4,AMARELA,120020.0,10.0,CRUZEIRO DO SUL,...,210012,FUNDACAO BUTANTAN,Organization/61189445000156,2021-02-18,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-02-19T21:53:14.000Z,NaN
8,005c7f34-2539-4d3a-895d-60abdd1dde10-i0b0,7988b2c4524d3475c8f14dfba74b3027569920f7499dac...,79,1941-06-10,F,5,INDIGENA,120005.0,10.0,ASSIS BRASIL,...,202010028,FUNDACAO BUTANTAN,Organization/61189445000156,2021-01-29,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-02-05T22:52:20.000Z,NaN
9,6b980351-362b-4e1c-9cda-a9449fa01fed-i0b0,8941005aba01dac94cd5671a7578811289fd0ca1c19b4b...,22,1998-06-27,F,3,PARDA,120020.0,10.0,CRUZEIRO DO SUL,...,210110,FUNDACAO BUTANTAN,Organization/61189445000156,2021-05-03,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-05-04T12:50:15.000Z,NaN

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169071 entries, 0 to 169070
Data columns (total 34 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   document_id                               169071 non-null  object
 1   paciente_id                               169071 non-null  object
 2   paciente_idade                            169071 non-null  int64
 3   paciente_datanascimento                   169071 non-null  object
 4   paciente_enumsexobiologico                169071 non-null  object
 5   paciente_racacor_codigo                   169071 non-null  int64
 6   paciente_racacor_valor                    169071 non-null  object
 7   paciente_endereco_coibgemunicipio         167802 non-null  float64
 8   paciente_endereco_copais                  167804 non-null  float64
 9   paciente_endereco_nmmunicipio             167804 non-null  object
 10  paciente_endereco_nmpais                  167804 non-null  object
 11  paciente_endereco_uf                      167802 non-null  object
 12  paciente_endereco_cep                     140711 non-null  float64
 13  paciente_nacionalidade_enumnacionalidade  168904 non-null  object
 14  estabelecimento_valor                     169071 non-null  int64
 15  estabelecimento_razaosocial               169071 non-null  object
 16  estalecimento_nofantasia                  169071 non-null  object
 17  estabelecimento_municipio_codigo          169071 non-null  int64
 18  estabelecimento_municipio_nome            169071 non-null  object
 19  estabelecimento_uf                        169071 non-null  object
 20  vacina_grupoatendimento_codigo            169071 non-null  int64
 21  vacina_grupoatendimento_nome              167965 non-null  object
 22  vacina_categoria_codigo                   167965 non-null  float64
 23  vacina_categoria_nome                     167467 non-null  object
 24  vacina_lote                               169071 non-null  object
 25  vacina_fabricante_nome                    169071 non-null  object
 26  vacina_fabricante_referencia              167680 non-null  object
 27  vacina_dataaplicacao                      169071 non-null  object
 28  vacina_descricao_dose                     169071 non-null  object
 29  vacina_codigo                             169071 non-null  int64
 30  vacina_nome                               169071 non-null  object
 31  sistema_origem                            169071 non-null  object
 32  data_importacao_rnds                      169071 non-null  object
 33  id_sistema_origem                         0 non-null       float64
dtypes: float64(5), int64(6), object(23)
memory usage: 43.9+ MB

In [26]:
# 1.

# Usando o método nunique na coluna vacina_nome obtemos a quantidade de vacinas dentro da base de dados

quantidade_vacinas = df['vacina_nome'].nunique()

quantidade_vacinas

5

In [27]:
# 2.

# Aqui realiza-se a mesma coisa do item anterior

pacientes_vacinados = df['paciente_id'].nunique()

pacientes_vacinados

120517

In [32]:
# 3. 

# Como o dado apresenta um caractere especial utilizou-se o método unique para ver como esses itens são descritos.

df['vacina_descricao_dose'].unique()

array(['\xa0\xa0\xa0\xa01ª\xa0Dose', '\xa0\xa0\xa0\xa02ª\xa0Dose',
       '\xa0\xa0\xa0\xa0Dose\xa0'], dtype=object)

In [44]:
# Depois realiza-se um filtro na base de dados e utiliza-se o shape para saber a quantidade de linhas.

primeira_vacina = df[df['vacina_descricao_dose'] == '\xa0\xa0\xa0\xa01ª\xa0Dose'].shape

primeira_vacina

(120939, 34)

In [53]:
# 4.

# Para saber quantos pessoas com menos de 18 anos foram vacinas vamos seguir as seguintes passo:

# Primeiro, vou remover dessa base de dados os ids que não toraram vacina.
# Segundo, filtrar para a idade menor que 18 anos.
# Verificar se não existem ids de pacientes iguais

df_pacientes_nao_vacinados = df[df['vacina_descricao_dose'] == '\xa0\xa0\xa0\xa0Dose\xa0']

df_pacientes_nao_vacinados.head()

,document_id,paciente_id,paciente_idade,paciente_datanascimento,paciente_enumsexobiologico,paciente_racacor_codigo,paciente_racacor_valor,paciente_endereco_coibgemunicipio,paciente_endereco_copais,paciente_endereco_nmmunicipio,...,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataaplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem,data_importacao_rnds,id_sistema_origem
3197,9e421c77-82e7-4486-8e31-b603b285456d-i0b0,6967ebaa1a872a6b8b194274f0b67019f4ea770a4423b3...,89,1931-07-22,M,1,BRANCA,120040.0,10.0,RIO BRANCO,...,210012,Janssen-Cilag,NaN,2021-02-22,Dose,88,Vacina covid-19 - Ad26.COV2.S - Janssen-Cilag,ESUS APS - NACIONAL (OFFLINE),2021-03-02T20:31:07.000Z,NaN
3199,9819b38f-7bc6-44cd-82bb-1cc79ed7a370-i0b0,c6d576e1172ccffdd878485f74deb52bbe6ee54dbd105a...,84,1937-01-11,M,3,PARDA,120080.0,10.0,PORTO ACRE,...,210012,Janssen-Cilag,NaN,2021-02-22,Dose,88,Vacina covid-19 - Ad26.COV2.S - Janssen-Cilag,ESUS APS - NACIONAL (OFFLINE),2021-03-02T20:31:07.000Z,NaN
3201,d0390d6c-0ba3-4ffb-a11b-e2ac729f74ad-i0b0,6a6c8e72c7e57042d0b6a4934d269c625751ab2461f2c9...,88,1932-11-10,F,3,PARDA,120045.0,10.0,SENADOR GUIOMARD,...,210012,Janssen-Cilag,NaN,2021-02-22,Dose,88,Vacina covid-19 - Ad26.COV2.S - Janssen-Cilag,ESUS APS - NACIONAL (OFFLINE),2021-03-02T20:31:07.000Z,NaN
49291,e6ab1219-2c4b-4d3f-98db-5c18d802136f-i0b0,097d5039bb1d9eb70e1b6830e253ee7dde35bb15b490cf...,85,1936-01-15,M,4,AMARELA,120080.0,10.0,PORTO ACRE,...,210012,Janssen-Cilag,NaN,2021-02-22,Dose,88,Vacina covid-19 - Ad26.COV2.S - Janssen-Cilag,ESUS APS - NACIONAL (OFFLINE),2021-03-02T20:31:07.000Z,NaN
49294,6d77b498-2cf5-42a2-be69-910a0345ddad-i0b0,c970f4697b02e64ebed7e89e3e1e287f96a0691e34dadd...,84,1936-06-21,F,4,AMARELA,120040.0,10.0,RIO BRANCO,...,210012,Janssen-Cilag,NaN,2021-02-22,Dose,88,Vacina covid-19 - Ad26.COV2.S - Janssen-Cilag,ESUS APS - NACIONAL (OFFLINE),2021-03-02T20:31:07.000Z,NaN

In [56]:
index_pacientes_nao_vacinados = df_pacientes_nao_vacinados.index

index_pacientes_nao_vacinados

Int64Index([  3197,   3199,   3201,  49291,  49294,  49297,  49300,  49303,
             49306,  49309,  49312,  49315,  49318,  75987,  75990,  75993,
             75996,  75999,  76002, 112743, 112745, 112747, 112749, 112751,
            112753],
           dtype='int64')

In [57]:
df_pacientes_vacinados = df.drop(index=index_pacientes_nao_vacinados)

In [58]:
pacientes_menor_18_vacinados = df_pacientes_vacinados[df_pacientes_vacinados['paciente_idade'] < 18]

pacientes_menor_18_vacinados.shape

(55, 34)

In [60]:
pacientes_menor_18_vacinados.nunique()

# 47 pacientes com idade menor que 18

document_id                                 54
paciente_id                                 47
paciente_idade                               9
paciente_datanascimento                     47
paciente_enumsexobiologico                   2
paciente_racacor_codigo                      5
paciente_racacor_valor                       5
paciente_endereco_coibgemunicipio           14
paciente_endereco_copais                     1
paciente_endereco_nmmunicipio               14
paciente_endereco_nmpais                     1
paciente_endereco_uf                         1
paciente_endereco_cep                       15
paciente_nacionalidade_enumnacionalidade     1
estabelecimento_valor                       18
estabelecimento_razaosocial                 14
estalecimento_nofantasia                    18
estabelecimento_municipio_codigo            13
estabelecimento_municipio_nome              13
estabelecimento_uf                           1
vacina_grupoatendimento_codigo              11
vacina_grupoatendimento_nome                10
vacina_categoria_codigo                      5
vacina_categoria_nome                        5
vacina_lote                                 11
vacina_fabricante_nome                       4
vacina_fabricante_referencia                 2
vacina_dataaplicacao                        39
vacina_descricao_dose                        2
vacina_codigo                                2
vacina_nome                                  2
sistema_origem                               2
data_importacao_rnds                        54
id_sistema_origem                            0
dtype: int64

In [61]:
# 5.

df.columns

Index(['document_id', 'paciente_id', 'paciente_idade',
       'paciente_datanascimento', 'paciente_enumsexobiologico',
       'paciente_racacor_codigo', 'paciente_racacor_valor',
       'paciente_endereco_coibgemunicipio', 'paciente_endereco_copais',
       'paciente_endereco_nmmunicipio', 'paciente_endereco_nmpais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumnacionalidade', 'estabelecimento_valor',
       'estabelecimento_razaosocial', 'estalecimento_nofantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf', 'vacina_grupoatendimento_codigo',
       'vacina_grupoatendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataaplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem', 'data_importacao_rnds', 'id_sistema_origem'],
      dtype='object')

In [68]:
# Utilizando o método nunique na coluna estalecimento_nofantasia determinamos a quantidade de estabelecimentos, 103.

df['estalecimento_nofantasia'].nunique()

103

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [151]:
# 1.

# Cópia do dataframe original, filtrando para menores de 18 anos

df_menor_18 = df[df['paciente_idade'] < 18]

In [174]:
df_menor_18.head()

,document_id,paciente_id,paciente_idade,paciente_datanascimento,paciente_enumsexobiologico,paciente_racacor_codigo,paciente_racacor_valor,paciente_endereco_coibgemunicipio,paciente_endereco_copais,paciente_endereco_nmmunicipio,...,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataaplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem,data_importacao_rnds,id_sistema_origem
1567,fdca313f-b348-422d-94d4-f2c66a87868c-i0b0,f5e6b8c44f7c4d13a87c582def5e8d460435b02f26af8c...,17,2003-07-18,F,4,AMARELA,120025.0,10.0,EPITACIOLANDIA,...,213VCD003W,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-05-12,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-05-13T16:16:42.000Z,NaN
6250,b7431955-1faa-4c1e-9246-7c1e7b8bb3cb-i0b0,e1a45c07e3c393d5f0eccf4204a7ceab338f4f06696ecb...,16,2004-05-18,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,200278,FUNDACAO BUTANTAN,Organization/61189445000156,2021-01-29,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-02-06T14:02:07.000Z,NaN
9569,fdb8d3b6-14d9-4bcc-9cfe-acd46b4a317a-i0b0,7cf3b238383a70eeb26841c01817737c9706d5b231e8c2...,17,2004-01-23,F,99,SEM INFORMACAO,120020.0,10.0,CRUZEIRO DO SUL,...,213VCD042Z,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-05-15,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-05-18T03:17:02.000Z,NaN
11338,647e2301-3ba4-463a-8d1e-2b6f38a4d99e-i0b0,53eb7fed5faa26ad17ce21ee378f28e25399ab7e90bc05...,17,2003-05-04,F,4,AMARELA,120030.0,10.0,FEIJO,...,4120Z004,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-02-09,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-02-09T22:08:13.000Z,NaN
15144,7f469e03-bece-49d0-bebc-33ad98e27f54-i0b0,dbaa6420d8a815158387668d0a59a19cf2bb63958e35d1...,16,2004-08-22,F,5,INDIGENA,120035.0,10.0,MARECHAL THAUMATURGO,...,202010028,FUNDACAO BUTANTAN,Organization/61189445000156,2021-01-28,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-02-09T19:26:03.000Z,NaN

In [168]:
# 2.

# Vizualizando quais são as colunas que tem no meu dataframe

df_menor_18.columns

Index(['document_id', 'paciente_id', 'paciente_idade',
       'paciente_datanascimento', 'paciente_enumsexobiologico',
       'paciente_racacor_codigo', 'paciente_racacor_valor',
       'paciente_endereco_coibgemunicipio', 'paciente_endereco_copais',
       'paciente_endereco_nmmunicipio', 'paciente_endereco_nmpais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumnacionalidade', 'estabelecimento_valor',
       'estabelecimento_razaosocial', 'estalecimento_nofantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf', 'vacina_grupoatendimento_codigo',
       'vacina_grupoatendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataaplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem', 'data_importacao_rnds', 'id_sistema_origem'],
      dtype='object')

In [158]:
# 3.

# Contagem do campo vacina_categoria_nome

# Não entendi muito bem o motivo de realizar essa contagem

df_menor_18['vacina_categoria_nome'].value_counts()

Povos Indígenas                     33
Trabalhadores de Saúde               9
Povos e Comunidades Tradicionais     9
Comorbidades                         2
Faixa Etária                         1
Name: vacina_categoria_nome, dtype: int64

In [177]:
# 4.

# Lista com as colunas dos estabelecimentos que serão utilizadas

lista_colunas_estabelecimentos = ['estabelecimento_valor', 
                                  'estabelecimento_razaosocial', 
                                  'estalecimento_nofantasia', 
                                  'estabelecimento_municipio_codigo', 
                                  'estabelecimento_municipio_nome', 
                                  'estabelecimento_uf']

In [ ]:
'estabelecimento_valor', 'estabelecimento_razaosocial', 'estalecimento_nofantasia', 'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome', 'estabelecimento_uf'

In [183]:
# 5.

# Esse é o dataframe resultante

df_estalecimentos_1 = df_menor_18.loc[:, lista_colunas_estabelecimentos]
df_estalecimentos_1.head()

,estabelecimento_valor,estabelecimento_razaosocial,estalecimento_nofantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
1567,2001314,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,ESF JOAO ALVES DA SILVA,120025,EPITACIOLANDIA,AC
6250,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
9569,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
11338,2000040,PREFEITURA MUNICIPAL DE FEIJO,CENTRO DE SAUDE DIAMANTINO MACEDO,120030,FEIJO,AC
15144,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC

In [194]:
# 6.

# Usando o método drop.duplicates eu removo os dados repetidos.

# Utiliei o método reset_index para resetar a contagem do index para facilitar na hora de chamar no loc para adicionar os valores à lista.

df_estab_limpa = df_estalecimentos_1.drop_duplicates()
df_estab_limpa.reset_index(inplace=True)
df_estab_limpa = df_estab_limpa.drop(columns='index')
df_estab_limpa

,estabelecimento_valor,estabelecimento_razaosocial,estalecimento_nofantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
0,2001314,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,ESF JOAO ALVES DA SILVA,120025,EPITACIOLANDIA,AC
1,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
2,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
3,2000040,PREFEITURA MUNICIPAL DE FEIJO,CENTRO DE SAUDE DIAMANTINO MACEDO,120030,FEIJO,AC
4,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
5,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
6,6308740,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE PORTO WALTER,120039,PORTO WALTER,AC
7,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
8,6917682,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
9,6428940,PREFEITURA MUNICIPAL DE ASSIS BRASIL,POLO BASE DE ASSIS BRASIL,120005,ASSIS BRASIL,AC
10,6612385,PREFEITURA MUNICIPAL DE TARAUACA,UNIDADE ASSISTENCIAL A SAUDE INDIGENA DE TARAU...,120060,TARAUACA,AC
11,9648968,DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ...,POLO INDIGENA DE MANOEL URBANO,120034,MANOEL URBANO,AC
12,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC
13,6955525,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MANCIO LIMA,120033,MANCIO LIMA,AC
14,5336171,SECRETARIA DE ESTADO DE SAUDE DO ACRE,HOSPITAL REGIONAL DO JURUA,120020,CRUZEIRO DO SUL,AC
15,6697151,MINISTERIO DA SAUDE,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO PURUS,120050,SENA MADUREIRA,AC
16,3323307,PREFEITURA MUNICIPAL DE PORTO ACRE,UNIDADE DE SAUDE DA FAMILIA ALVARO ARAUJO NOBRE,120080,PORTO ACRE,AC
17,7123043,PREFEITURA MUNICIPAL DE JORDAO,SAUDE DA FAMILIA RIBEIRINHA,120032,JORDAO,AC

In [201]:
# Criei uma lista para cada um dos dados do estabelecimento com seus respectivos dados.

lista_estabelecimentos = []

i = 0

while i < 18:
    lista_estabelecimentos.append(df_estab_limpa.loc[i, lista_colunas_estabelecimentos])
    i += 1 


lista_estabelecimentos

[estabelecimento_valor                                              2001314
 estabelecimento_razaosocial         PREFEITURA MUNICIPAL DE EPITACIOLANDIA
 estalecimento_nofantasia                           ESF JOAO ALVES DA SILVA
 estabelecimento_municipio_codigo                                    120025
 estabelecimento_municipio_nome                              EPITACIOLANDIA
 estabelecimento_uf                                                      AC
 Name: 0, dtype: object,
 estabelecimento_valor                                                         6917291
 estabelecimento_razaosocial                        PREFEITURA MUNICIPAL DE RIO BRANCO
 estalecimento_nofantasia            DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...
 estabelecimento_municipio_codigo                                               120040
 estabelecimento_municipio_nome                                             RIO BRANCO
 estabelecimento_uf                                                                 AC
 Name: 1, dtype: object,
 estabelecimento_valor                                                        6159087
 estabelecimento_razaosocial                  PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL
 estalecimento_nofantasia            SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL
 estabelecimento_municipio_codigo                                              120020
 estabelecimento_municipio_nome                                       CRUZEIRO DO SUL
 estabelecimento_uf                                                                AC
 Name: 2, dtype: object,
 estabelecimento_valor                                         2000040
 estabelecimento_razaosocial             PREFEITURA MUNICIPAL DE FEIJO
 estalecimento_nofantasia            CENTRO DE SAUDE DIAMANTINO MACEDO
 estabelecimento_municipio_codigo                               120030
 estabelecimento_municipio_nome                                  FEIJO
 estabelecimento_uf                                                 AC
 Name: 3, dtype: object,
 estabelecimento_valor                                                         7625855
 estabelecimento_razaosocial         DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...
 estalecimento_nofantasia                            POLO BASE DE MARECHAL THAUMATURGO
 estabelecimento_municipio_codigo                                               120035
 estabelecimento_municipio_nome                                   MARECHAL THAUMATURGO
 estabelecimento_uf                                                                 AC
 Name: 4, dtype: object,
 estabelecimento_valor                                                         6748759
 estabelecimento_razaosocial         DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...
 estalecimento_nofantasia                                           POLO BASE DE FEIJO
 estabelecimento_municipio_codigo                                               120030
 estabelecimento_municipio_nome                                                  FEIJO
 estabelecimento_uf                                                                 AC
 Name: 5, dtype: object,
 estabelecimento_valor                                                         6308740
 estabelecimento_razaosocial         DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...
 estalecimento_nofantasia                                    POLO BASE DE PORTO WALTER
 estabelecimento_municipio_codigo                                               120039
 estabelecimento_municipio_nome                                           PORTO WALTER
 estabelecimento_uf                                                                 AC
 Name: 6, dtype: object,
 estabelecimento_valor                                            2001748
 estabelecimento_razaosocial         PREFEITURA MUNICIPAL DE PORTO WALTER
 estalecimento_nofantasia                   UBS VICENTE VARELA DE ALMEIDA
 estabelecimento_municipio_codigo                                  120039
 estabelecimento_municipio_nome                              PORTO WALTER
 estabelecimento_uf                                                    AC
 Name: 7, dtype: object,
 estabelecimento_valor                                                         6917682
 estabelecimento_razaosocial         DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...
 estalecimento_nofantasia                                 POLO BASE DE CRUZEIRO DO SUL
 estabelecimento_municipio_codigo                                               120020
 estabelecimento_municipio_nome                                        CRUZEIRO DO SUL
 estabelecimento_uf                                                                 AC
 Name: 8, dtype: object,
 estabelecimento_valor                                            6428940
 estabelecimento_razaosocial         PREFEITURA MUNICIPAL DE ASSIS BRASIL
 estalecimento_nofantasia                       POLO BASE DE ASSIS BRASIL
 estabelecimento_municipio_codigo                                  120005
 estabelecimento_municipio_nome                              ASSIS BRASIL
 estabelecimento_uf                                                    AC
 Name: 9, dtype: object,
 estabelecimento_valor                                                         6612385
 estabelecimento_razaosocial                          PREFEITURA MUNICIPAL DE TARAUACA
 estalecimento_nofantasia            UNIDADE ASSISTENCIAL A SAUDE INDIGENA DE TARAU...
 estabelecimento_municipio_codigo                                               120060
 estabelecimento_municipio_nome                                               TARAUACA
 estabelecimento_uf                                                                 AC
 Name: 10, dtype: object,
 estabelecimento_valor                                                         9648968
 estabelecimento_razaosocial         DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ...
 estalecimento_nofantasia                               POLO INDIGENA DE MANOEL URBANO
 estabelecimento_municipio_codigo                                               120034
 estabelecimento_municipio_nome                                          MANOEL URBANO
 estabelecimento_uf                                                                 AC
 Name: 11, dtype: object,
 estabelecimento_valor                                                       6430201
 estabelecimento_razaosocial         DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA
 estalecimento_nofantasia                                         POLO BASE INDIGENA
 estabelecimento_municipio_codigo                                             120032
 estabelecimento_municipio_nome                                               JORDAO
 estabelecimento_uf                                                               AC
 Name: 12, dtype: object,
 estabelecimento_valor                                                         6955525
 estabelecimento_razaosocial         DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...
 estalecimento_nofantasia                                     POLO BASE DE MANCIO LIMA
 estabelecimento_municipio_codigo                                               120033
 estabelecimento_municipio_nome                                            MANCIO LIMA
 estabelecimento_uf                                                                 AC
 Name: 13, dtype: object,
 estabelecimento_valor                                             5336171
 estabelecimento_razaosocial         SECRETARIA DE ESTADO DE SAUDE DO ACRE
 estalecimento_nofantasia                       HOSPITAL REGIONAL DO JURUA
 estabelecimento_municipio_codigo                                   120020
 estabelecimento_municipio_nome                            CRUZEIRO DO SUL
 estabelecimento_uf                                                     AC
 Name: 14, dtype: object,
 estabelecimento_valor                                                       6697151
 estabelecimento_razaosocial                                     MINISTERIO DA SAUDE
 estalecimento_nofantasia            DISTRITO SANITARIO ESPECIAL INDIGENA ALTO PURUS
 estabelecimento_municipio_codigo                                             120050
 estabelecimento_municipio_nome                                       SENA MADUREIRA
 estabelecimento_uf                                                               AC
 Name: 15, dtype: object,
 estabelecimento_valor                                                       3323307
 estabelecimento_razaosocial                      PREFEITURA MUNICIPAL DE PORTO ACRE
 estalecimento_nofantasia            UNIDADE DE SAUDE DA FAMILIA ALVARO ARAUJO NOBRE
 estabelecimento_municipio_codigo                                             120080
 estabelecimento_municipio_nome                                           PORTO ACRE
 estabelecimento_uf                                                               AC
 Name: 16, dtype: object,
 estabelecimento_valor                                      7123043
 estabelecimento_razaosocial         PREFEITURA MUNICIPAL DE JORDAO
 estalecimento_nofantasia               SAUDE DA FAMILIA RIBEIRINHA
 estabelecimento_municipio_codigo                            120032
 estabelecimento_municipio_nome                              JORDAO
 estabelecimento_uf                                              AC
 Name: 17, dtype: object]

#### Obs.:
A partir daqui é um sequencia de código que eu fiz sem usar a sequência de itens, porque eu pensei que tinha que fazer o que estava escrito no enunciado e depois fazer o que estava nos itens.

In [101]:
# Criando o dataframe apenas com os estabelecimentos que aplicaram vacinas a menores de 18 anos.

df_menor_18 = df[df['paciente_idade'] < 18]

In [91]:
# Criei uma lista com as colunas que deveriam ser excluídas do dataframe, mantendo apenas as colunas que tem dados dos estabelecimentos.

drop_list = ['document_id', 'paciente_id', 'paciente_idade',
       'paciente_datanascimento', 'paciente_enumsexobiologico',
       'paciente_racacor_codigo', 'paciente_racacor_valor',
       'paciente_endereco_coibgemunicipio', 'paciente_endereco_copais',
       'paciente_endereco_nmmunicipio', 'paciente_endereco_nmpais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumnacionalidade', 'vacina_grupoatendimento_codigo',
       'vacina_grupoatendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataaplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem', 'data_importacao_rnds', 'id_sistema_origem']

In [135]:
# Dataframe sem as colunas da lista

df_estabelecimentos = df_menor_18.drop(columns=drop_list)

In [134]:
# Usei o método value_counts para contar a quantidade de vezes que cada estabelecimento aparece, que também é a quantidade de vacidas que eles deram em pessoas com menos de 18 anos.

qt_vacinas = df_estabelecimentos['estalecimento_nofantasia'].value_counts()
qt_vacinas

POLO BASE DE MARECHAL THAUMATURGO                              9
UBS VICENTE VARELA DE ALMEIDA                                  8
POLO BASE DE FEIJO                                             6
DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AMBIENTAL          4
POLO BASE INDIGENA                                             4
POLO BASE DE ASSIS BRASIL                                      3
SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL               3
CENTRO DE SAUDE DIAMANTINO MACEDO                              3
POLO BASE DE MANCIO LIMA                                       3
POLO BASE DE PORTO WALTER                                      2
UNIDADE ASSISTENCIAL A SAUDE INDIGENA DE TARAUACA POLO BASE    2
POLO INDIGENA DE MANOEL URBANO                                 2
DISTRITO SANITARIO ESPECIAL INDIGENA ALTO PURUS                1
UNIDADE DE SAUDE DA FAMILIA ALVARO ARAUJO NOBRE                1
ESF JOAO ALVES DA SILVA                                        1
HOSPITAL REGIONAL DO JURUA                                     1
POLO BASE DE CRUZEIRO DO SUL                                   1
SAUDE DA FAMILIA RIBEIRINHA                                    1
Name: estalecimento_nofantasia, dtype: int64

In [145]:
# Com a minha base de dados eu removi os dados duplicados e dei um reset no index.

df_estabelecimentos_s_repetir = df_estabelecimentos.drop_duplicates(keep='first')
df_estabelecimentos_s_repetir = df_estabelecimentos_s_repetir.reset_index()
df_estabelecimentos_s_repetir = df_estabelecimentos_s_repetir.drop(columns='index')
df_estabelecimentos_s_repetir

,estabelecimento_valor,estabelecimento_razaosocial,estalecimento_nofantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
0,2001314,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,ESF JOAO ALVES DA SILVA,120025,EPITACIOLANDIA,AC
1,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
2,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
3,2000040,PREFEITURA MUNICIPAL DE FEIJO,CENTRO DE SAUDE DIAMANTINO MACEDO,120030,FEIJO,AC
4,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
5,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
6,6308740,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE PORTO WALTER,120039,PORTO WALTER,AC
7,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
8,6917682,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
9,6428940,PREFEITURA MUNICIPAL DE ASSIS BRASIL,POLO BASE DE ASSIS BRASIL,120005,ASSIS BRASIL,AC
10,6612385,PREFEITURA MUNICIPAL DE TARAUACA,UNIDADE ASSISTENCIAL A SAUDE INDIGENA DE TARAU...,120060,TARAUACA,AC
11,9648968,DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ...,POLO INDIGENA DE MANOEL URBANO,120034,MANOEL URBANO,AC
12,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC
13,6955525,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MANCIO LIMA,120033,MANCIO LIMA,AC
14,5336171,SECRETARIA DE ESTADO DE SAUDE DO ACRE,HOSPITAL REGIONAL DO JURUA,120020,CRUZEIRO DO SUL,AC
15,6697151,MINISTERIO DA SAUDE,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO PURUS,120050,SENA MADUREIRA,AC
16,3323307,PREFEITURA MUNICIPAL DE PORTO ACRE,UNIDADE DE SAUDE DA FAMILIA ALVARO ARAUJO NOBRE,120080,PORTO ACRE,AC
17,7123043,PREFEITURA MUNICIPAL DE JORDAO,SAUDE DA FAMILIA RIBEIRINHA,120032,JORDAO,AC

In [149]:
# Criei uma lista com a quantidade de vacinas dadas em cada estabelecimento na ordem da minha base de dados.

qt_vacinas_lista = [1, 4, 3, 3, 9, 6, 2, 8, 1, 3, 2, 2, 4, 3, 1, 1, 1, 1]

# Transformei a lista em uma série para que ela pudesse ser adiciona como uma coluna no meu dataframe

qt_vacinas = pd.Series(qt_vacinas_lista)
qt_vacinas

0     1
1     4
2     3
3     3
4     9
5     6
6     2
7     8
8     1
9     3
10    2
11    2
12    4
13    3
14    1
15    1
16    1
17    1
dtype: int64

In [150]:
# Criei uma nova coluna com os dados de quantidade de vacinas

df_estabelecimentos_s_repetir['qt_pacientes'] = qt_vacinas

df_estabelecimentos_s_repetir

,estabelecimento_valor,estabelecimento_razaosocial,estalecimento_nofantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf,qt_pacientes
0,2001314,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,ESF JOAO ALVES DA SILVA,120025,EPITACIOLANDIA,AC,1
1,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC,4
2,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC,3
3,2000040,PREFEITURA MUNICIPAL DE FEIJO,CENTRO DE SAUDE DIAMANTINO MACEDO,120030,FEIJO,AC,3
4,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC,9
5,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC,6
6,6308740,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE PORTO WALTER,120039,PORTO WALTER,AC,2
7,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC,8
8,6917682,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC,1
9,6428940,PREFEITURA MUNICIPAL DE ASSIS BRASIL,POLO BASE DE ASSIS BRASIL,120005,ASSIS BRASIL,AC,3
10,6612385,PREFEITURA MUNICIPAL DE TARAUACA,UNIDADE ASSISTENCIAL A SAUDE INDIGENA DE TARAU...,120060,TARAUACA,AC,2
11,9648968,DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ...,POLO INDIGENA DE MANOEL URBANO,120034,MANOEL URBANO,AC,2
12,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC,4
13,6955525,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MANCIO LIMA,120033,MANCIO LIMA,AC,3
14,5336171,SECRETARIA DE ESTADO DE SAUDE DO ACRE,HOSPITAL REGIONAL DO JURUA,120020,CRUZEIRO DO SUL,AC,1
15,6697151,MINISTERIO DA SAUDE,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO PURUS,120050,SENA MADUREIRA,AC,1
16,3323307,PREFEITURA MUNICIPAL DE PORTO ACRE,UNIDADE DE SAUDE DA FAMILIA ALVARO ARAUJO NOBRE,120080,PORTO ACRE,AC,1
17,7123043,PREFEITURA MUNICIPAL DE JORDAO,SAUDE DA FAMILIA RIBEIRINHA,120032,JORDAO,AC,1